language: node_js
os: linux
dist: xenial

jobs:
  include:
    - node_js: stable
      script: standard
      name: Lint
    - node_js: stable
      script: npm run test:ci
    - node_js: 12
      script: npm run test:ci
    - node_js: 10
      script: npm run test:ci
    - node_js: 8
      script: npm run test:ci
    - node_js: 6
      script: npm run test:ci
    - node_js: 4
      script: npm run test:ci
    - node_js: '0.12'
      script: npm run test:ci
    - node_js: '0.10'
      script: npm run test:ci
    - node_js: '0.8'
      script: npm run test:ci
